# Generated by Django 6.0.5 on 2026-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bug_description', models.TextField()),
                ('status', models.CharField(choices=[('analyzing', 'Analyzing'), ('test_failed', 'Test Failed'), ('fixed', 'Fixed')], default='analyzing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
