# Generated by Django 6.0.5 on 2026-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_businessevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessevaluation',
            name='ai_base_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
